# mysql Setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql=true: true
        format_sql: true
        use_sql_comments: true
