# mysql Setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manage?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql=true: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: none
    database: mysql
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
